name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  clangd-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip vim libusb-1.0-0

      - name: "Run clangd tests"
        run: |
          cd test/clangd
          chmod +x test.sh
          ./test.sh
  ncs-toolchain-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip vim libusb-1.0-0

      - name: "Run NCS Toolchain tests"
        run: |
          cd test/ncs_toolchain
          chmod +x test.sh
          ./test.sh

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4



      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .

